"""empty message

Revision ID: dc36b66449c1
Revises: e900acc6e0f5
Create Date: 2020-08-12 17:29:58.240687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc36b66449c1'
down_revision = 'e900acc6e0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'new', 'user', ['u_id'], ['id'])
    op.create_foreign_key(None, 'new', 'newstype', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'new', type_='foreignkey')
    op.drop_constraint(None, 'new', type_='foreignkey')
    # ### end Alembic commands ###
